Add key-type specific en- / decoder
open-quantum-safe/oqs-provider pull request #597
Opened 2024-12-20 04:44 UTC by wbeck10

Encoding and decoding of oqs keys using type specific en- / decoding is not working.
This pull requests adds type specific key der en- / decoding.

This PR will solve Fixes https://github.com/open-quantum-safe/oqs-provider/issues/562

2024-12-20 07:05 UTC, baentsch requested changes
Thanks @wbeck10 -- much better with the use of the jinja code generation logic! At first glance this looks OK but can I ask you to run the code formatter as per https://github.com/open-quantum-safe/oqs-provider/blob/main/CONTRIBUTING.md#coding-style and check the result in such as to be able to run all tests in CI? Getting "DCO" to green would also be nice, but I'm not hung up on that.

2024-12-20 17:01 UTC, ryjones commented
`git commit --amend --author="Wolfgang Beck <beck.wolfgang@oracle.com>" --no-edit`

Per-repo:
`git config user.email "beck.wolfgang@oracle.com"`

If you want it global:
`git config --global user.email "beck.wolfgang@oracle.com"`

`git push --force-with-lease origin encdec3`

2025-01-06 10:44 UTC, baentsch commented
@wbeck10 please see guidance of @ryjones on "DCO"; also, re-based needed.

2025-01-13 00:33 UTC, wbeck10 commented
> Thanks @wbeck10 -- much better with the use of the jinja code generation logic! At first glance this looks OK but can I ask you to run the code formatter as per https://github.com/open-quantum-safe/oqs-provider/blob/main/CONTRIBUTING.md#coding-style and check the result in such as to be able to run all tests in CI? Getting "DCO" to green would also be nice, but I'm not hung up on that.

Sorry for the delay. I had a couple of weeks holiday :). I've fixed the formatter issues.

2025-01-14 00:57 UTC, wbeck10 commented
I don't know why the macOS-noopenssl test is failing with:
error registering mldsa44 with no hash

I don't think this is caused by my changes.

2025-01-14 06:12 UTC, baentsch commented
No worries, this is due to #621: oqsprovider needs to change its algorithm names and code generation logic substantially.

2025-01-16 22:21 UTC, wbeck10 commented
The windows test codestyle reports an error:
Run ./scripts/do_code_format.sh
oqsprov/oqsprov.c:67[4](https://github.com/open-quantum-safe/oqs-provider/actions/runs/12738485098/job/35535674645?pr=597#step:5:5):52: error: code should be clang-formatted [-Wclang-format-violations]
static const OSSL_ALGORITHM oqsprovider_keymgmt[] = {
                                                   ^
oqsprov/oqsprov.c:848:7: error: code should be clang-formatted [-Wclang-format-violations]
#endif
      ^
oqsprov/oqsprov.c:849:23: error: code should be clang-formatted [-Wclang-format-violations]
    // clang-format on
                      ^
oqsprov/oqsprov.c:8[5](https://github.com/open-quantum-safe/oqs-provider/actions/runs/12738485098/job/35535674645?pr=597#step:5:6)0:54: error: code should be clang-formatted [-Wclang-format-violations]
    ///// OQS_TEMPLATE_FRAGMENT_KEYMGMT_FUNCTIONS_END
                                                     ^
oqsprov/oqs_sig.c:13[6](https://github.com/open-quantum-safe/oqs-provider/actions/runs/12738485098/job/35535674645?pr=597#step:5:7)9:19: error: code should be clang-formatted [-Wclang-format-violations]
    OSSL_PARAM_END
                  ^
Error: Some files need reformatting. Check output above.


I'm not getting this on Linux.
Do I need to fix something?

2025-01-20 19:52 UTC, SWilson4 commented
> I'm not getting this on Linux. Do I need to fix something?

If you run `scripts/format_code.sh`, that should format the code in the same Docker container that we use for CI. Sometimes different versions of formatting tools are incompatible.

2025-02-20 09:34 UTC, baentsch commented
@wbeck10 fyi, the system finally should build and run CI successfully again. So if you'd still like to contribute this (?) please re-base and re-run CI. Otherwise, please close the PR.

2025-09-09 09:16 UTC, baentsch commented
Closing after a long-time of no further interactions. Please re-open if you'd still like to land this @wbeck10 .

2025-09-09 09:16 UTC, closed without merging